application: skykit-display-device-int  # DO NOT CHANGE THIS!  To deploy to other environments, use the command line
version: snapshot
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.3"
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"
- name: MySQLdb
  version: "latest"

handlers:
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  login: required

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /scripts
  static_dir: static/scripts

- url: /styles
  static_dir: static/styles

- url: /img
  static_dir: static/assets/images

- url: /fonts
  static_dir: static/fonts

- url: /assets/images
  static_dir: web/images

- url: /migrate
  script: routes.application
  login: admin
  secure: always

- url: /api-docs
  static_files: documentation/api.html
  upload: documentation/api.html
  login: required
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required
  secure: always
  auth_fail_action: redirect

- url: /static
  static_dir: static

- url: /bower_components
  static_dir: webapp/bower_components

- url: /app
  static_dir: web/client/app

- url: /dist
  static_dir: static

- url: /web
  static_dir: web

- url: /dev/.*
  login: admin
  script: routes.application
  secure: always

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: routes.application
  secure: always

skip_files:
- ^coverage/.*$
- ^coverage_html_report/.*$
- ^scripts/.*
- ^images/readme.md
- ^local/.*
- ^tests/.*
- ^webapp/node_modules/.*$
- ^webapp/dist/.*$
- ^webapp/specs/.*$
- ^webapp/coverage/.*$
- ^.git/.*$
- ^backup/.git/.*
- ^.idea/.*
- ^.venv2/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
- ^.*\.egg-info
- ^\.DS_Store.*
- ^(.*/)?.*static/node_modules/.*
