application: proactiveservices-int  # DO NOT CHANGE THIS!  To deploy to other environments, use the command line
version: snapshot
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.3"
- name: webapp2
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /favicon\.ico
  static_files: static/app/images/favicon.ico
  upload: static/app/images/favicon\.ico

- url: /bower_components
  static_dir: static/app/bower_components

- url: /scripts
  static_dir: static/app/scripts

- url: /styles
  static_dir: static/app/styles

- url: /img
  static_dir: static/app/images

- url: /fonts
  static_dir: static/app/fonts

- url: /images
  static_dir: static/app/images

- url: /views
  static_dir: static/app/views

- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /mapreduce(/.*)?
  script: mapreduce.main.mapreduce_app
  login: admin

- url: /events
  script: routes.application

- url: /dev/views
  static_dir: templates/dev/views

- url: /dev/scripts
  static_dir: templates/dev/scripts

- url: /dev
  login: admin
  script: routes.application

- url: /migrate
  login: admin
  script: routes.application

- url: /tasks
  login: admin
  script: routes.application

- url: /.*
  script: routes.application
  secure: optional



skip_files:
- ^coverage/.*
- ^coverage_html_report/.*
- ^migration/.*
- ^monitor/.*
- ^export/.*
- ^pa/.*
- ^scripts/.*
- ^snapdeploy.yaml
- ^images/readme.md
- ^local/.*
- ^tests/.*
- ^simtests/.*
- ^static/app/node_modules/.*
- ^.hg/.*
- ^.idea/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
- ^.*\.egg-info
- ^\.DS_Store.*
- ^(.*/)?.*static/node_modules/.*
