application: skykit-display-device-int  # DO NOT CHANGE THIS!  To deploy to other environments, use the command line
version: snapshot
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.3"
- name: webapp2
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  login: required

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /bower_components
  static_dir: static/app/bower_components

- url: /scripts
  static_dir: static/scripts

- url: /styles
  static_dir: static/styles

- url: /img
  static_dir: static/assets/images

- url: /fonts
  static_dir: static/fonts

- url: /images
  static_dir: static/assets/images

- url: /migrate
  login: admin
  script: routes.application

- url: /
  static_files: static/index.html
  upload: static/index.html
#  login: required

- url: /.*
  script: routes.application
#  secure: optional
#  login: required



skip_files:
- ^coverage/.*
- ^coverage_html_report/.*
- ^migration/.*
- ^monitor/.*
- ^export/.*
- ^pa/.*
- ^scripts/.*
- ^snapdeploy.yaml
- ^images/readme.md
- ^local/.*
- ^tests/.*
- ^simtests/.*
- ^webapp/.*
- ^.git/.*
- ^.idea/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
- ^.*\.egg-info
- ^\.DS_Store.*
- ^(.*/)?.*static/node_modules/.*
