"""Add information to locations table

Revision ID: 104ab80ef5e7
Revises: 4f138efe4e77
Create Date: 2016-02-10 17:44:19.733429

"""

# revision identifiers, used by Alembic.
revision = '104ab80ef5e7'
down_revision = '4f138efe4e77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('location', sa.Column('dma_code', sa.String(length=255), nullable=True))
    op.add_column('location', sa.Column('state', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'state')
    op.drop_column('location', 'dma_code')
    op.drop_column('location', 'city')
    ### end Alembic commands ###
