"""make chromeosdevice table

Revision ID: 27b6a76880d9
Revises: 26897be49a43
Create Date: 2016-11-29 12:50:07.258219

"""

# revision identifiers, used by Alembic.
revision = '27b6a76880d9'
down_revision = '26897be49a43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chrome_os_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chrome_os_device')
    ### end Alembic commands ###
