"""location code nullable

Revision ID: 3b3e2894f5dc
Revises: 232a04cacb61
Create Date: 2016-02-26 15:22:15.023044

"""

# revision identifiers, used by Alembic.
revision = '3b3e2894f5dc'
down_revision = '232a04cacb61'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'customer_location_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'customer_location_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
