"""setup default logging models

Revision ID: 4f138efe4e77
Revises: None
Create Date: 2016-02-08 10:13:55.187551

"""

# revision identifiers, used by Alembic.
revision = '4f138efe4e77'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_play_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('device_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_code', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_identifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_identifier')
    )
    op.create_table('gamestop_store_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_identifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_identifier'),
    sa.UniqueConstraint('resource_name')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('device_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_code', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_went_live',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule')
    )
    op.create_table('program_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_record')
    op.drop_table('schedule_went_live')
    op.drop_table('device')
    op.drop_table('resource')
    op.drop_table('gamestop_store_location')
    op.drop_table('location')
    op.drop_table('program_play_event')
    ### end Alembic commands ###
